title = "DemoGo - Amazon ECS Cats and Dogs"
googleAnalytics = "UA-162159643-1"
anguageCode = "ko-KR"
defaultContentLanguage = "ko"
theme = "hugo-theme-learn"
showHeaderLanguageChooser=true
defaultContentLanguageInSubdir= true
#metaDataFormat = "yaml"
#baseURL = ""

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableInlineCopyToClipBoard = false
  author = "Jimin Kim"

[[menu.shortcuts]] 
  name = "<i class='fab fa-aws'></i> ECS Workshop"
  url = "https://ecsworkshop.com/"
  weight = 1000

[[menu.shortcuts]] 
  name = "<i class='fab fa-aws'></i> EKS Workshop"
  url = "https://eksworkshop.com/"
  weight = 1010

[[menu.shortcuts]] 
  name = "<i class='fab fa-aws'></i> AppMesh Workshop"
  url = "https://www.appmeshworkshop.com/"
  weight = 1020

[[menu.shortcuts]]
  name = "<i class='fas fa-blog'></i> AWS Container Blog"
  url = "https://aws.amazon.com/blogs/?awsf.blog-master-category=category%23containers"
  weight = 1030


#[[menu.shortcuts]]
#  name = "<i class='fab fa-facebook-square'></i> Facebook"
#  url = "https://www.facebook.com/groups/awskrug/"
#  weight = 1030

[[menu.shortcuts]]
  name = "<i class='fab fa-github'></i> Github"
  url = "https://github.com/aws-samples/amazon-ecs-for-beginners-catsdogs"
  weight = 1040

[Languages]
  [Languages.ko]
    weight = 1
    languageName = "한국어"

  [Languages.en]
    weight = 2
    languageName = "English"

[deployment]
  [[deployment.targets]]
    name = "s3"
    URL = "s3://ecs.catsdogs.kr/catsdogs?region=ap-northeast-2"
